-- ============================================================
-- NEXA PLATFORM — TAXONOMIA OFICIAL DO ENEM
-- Trilhas, Subtrilhas e Habilidades Pedagógicas
-- Baseado na Matriz de Referência Oficial (INEP/MEC)
-- Data: 2026-05
-- ============================================================
-- ⚠️  ATENÇÃO: Este script reinicia todos os dados de trilhas.
--     Execute no Editor SQL do Supabase após confirmar limpeza.
-- ============================================================

-- Limpeza em cascata (mantém estrutura das tabelas)
TRUNCATE TABLE exercicios_subtrilha    RESTART IDENTITY CASCADE;
TRUNCATE TABLE conteudos_subtrilha     RESTART IDENTITY CASCADE;
TRUNCATE TABLE progresso_subtrilha     RESTART IDENTITY CASCADE;
TRUNCATE TABLE subtrilhas              RESTART IDENTITY CASCADE;
TRUNCATE TABLE habilidades_pedagogicas RESTART IDENTITY CASCADE;
DELETE FROM public.trilhas;


-- ============================================================
-- 1. TRILHAS (5 Áreas de Conhecimento)
-- ============================================================

INSERT INTO public.trilhas (id, titulo, descricao) VALUES
  ('00000000-1000-0000-0000-000000000001',
   'Linguagens, Códigos e suas Tecnologias',
   'Interpretação de texto, literatura, língua portuguesa, inglês, artes e tecnologias da comunicação — conforme a Matriz ENEM.'),

  ('00000000-2000-0000-0000-000000000001',
   'Matemática e suas Tecnologias',
   'Números, geometria, grandezas, álgebra, funções, estatística e probabilidade — conforme a Matriz ENEM.'),

  ('00000000-3000-0000-0000-000000000001',
   'Ciências da Natureza e suas Tecnologias',
   'Física, química, biologia e ciência-tecnologia-sociedade — conforme a Matriz ENEM.'),

  ('00000000-4000-0000-0000-000000000001',
   'Ciências Humanas e suas Tecnologias',
   'História, geografia, filosofia, sociologia, cidadania e meio ambiente — conforme a Matriz ENEM.'),

  ('00000000-5000-0000-0000-000000000001',
   'Redação ENEM',
   'Estrutura dissertativo-argumentativa, competências avaliadas, repertório sociocultural e proposta de intervenção.');


-- ============================================================
-- 2. HABILIDADES PEDAGÓGICAS (Matriz Oficial — H1 a H30 por área)
-- Prefixo de ID: LCT = Linguagens | MAT = Matemática
--                CNT = Ciências da Natureza | CHT = Ciências Humanas
-- ============================================================

INSERT INTO habilidades_pedagogicas (id, nome, descricao, area_conhecimento, depende_de) VALUES

-- ─── LINGUAGENS ───────────────────────────────────────────
('LCT_H01', 'LCT H1 — Linguagens dos sistemas de comunicação',
 'Identificar as diferentes linguagens e seus recursos expressivos como elementos de caracterização dos sistemas de comunicação.',
 'Linguagens', NULL),
('LCT_H02', 'LCT H2 — Uso das linguagens para resolução de problemas sociais',
 'Recorrer aos conhecimentos sobre linguagens dos sistemas de comunicação e informação para resolver problemas sociais.',
 'Linguagens', 'LCT_H01'),
('LCT_H03', 'LCT H3 — Informações dos sistemas de comunicação',
 'Relacionar informações geradas nos sistemas de comunicação e informação, considerando a função social desses sistemas.',
 'Linguagens', 'LCT_H01'),
('LCT_H04', 'LCT H4 — Posições críticas sobre linguagens e comunicação',
 'Reconhecer posições críticas aos usos sociais que são feitos das linguagens e dos sistemas de comunicação e informação.',
 'Linguagens', 'LCT_H01'),

('LCT_H05', 'LCT H5 — Vocabulário em língua estrangeira',
 'Associar vocábulos e expressões de um texto em LEM ao seu tema.',
 'Linguagens', NULL),
('LCT_H06', 'LCT H6 — Acesso a informações via língua estrangeira',
 'Utilizar os conhecimentos da LEM como meio de ampliar as possibilidades de acesso a informações, tecnologias e culturas.',
 'Linguagens', 'LCT_H05'),
('LCT_H07', 'LCT H7 — Estruturas linguísticas e função social em LEM',
 'Relacionar um texto em LEM, as estruturas linguísticas, sua função e seu uso social.',
 'Linguagens', 'LCT_H05'),
('LCT_H08', 'LCT H8 — Diversidade cultural e linguística em LEM',
 'Reconhecer a importância da produção cultural em LEM como representação da diversidade cultural e linguística.',
 'Linguagens', 'LCT_H05'),

('LCT_H09', 'LCT H9 — Linguagem corporal e cotidiano',
 'Reconhecer as manifestações corporais de movimento como originárias de necessidades cotidianas de um grupo social.',
 'Linguagens', NULL),
('LCT_H10', 'LCT H10 — Transformação de hábitos corporais',
 'Reconhecer a necessidade de transformação de hábitos corporais em função das necessidades cinestésicas.',
 'Linguagens', 'LCT_H09'),
('LCT_H11', 'LCT H11 — Linguagem corporal e interação social',
 'Reconhecer a linguagem corporal como meio de interação social, considerando os limites de desempenho e alternativas de adaptação.',
 'Linguagens', 'LCT_H09'),

('LCT_H12', 'LCT H12 — Funções da arte',
 'Reconhecer diferentes funções da arte e do trabalho dos artistas em seus meios culturais.',
 'Linguagens', NULL),
('LCT_H13', 'LCT H13 — Arte, cultura e preconceito',
 'Analisar as diversas produções artísticas como meio de explicar diferentes culturas, padrões de beleza e preconceitos.',
 'Linguagens', 'LCT_H12'),
('LCT_H14', 'LCT H14 — Diversidade artística',
 'Reconhecer o valor da diversidade artística e das inter-relações entre diferentes grupos sociais e étnicos.',
 'Linguagens', 'LCT_H12'),

('LCT_H15', 'LCT H15 — Texto literário e contexto histórico',
 'Estabelecer relações entre o texto literário e o momento de sua produção, situando aspectos do contexto histórico, social e político.',
 'Linguagens', NULL),
('LCT_H16', 'LCT H16 — Concepções artísticas e construção literária',
 'Relacionar informações sobre concepções artísticas e procedimentos de construção do texto literário.',
 'Linguagens', 'LCT_H15'),
('LCT_H17', 'LCT H17 — Valores no patrimônio literário nacional',
 'Reconhecer a presença de valores sociais e humanos atualizáveis no patrimônio literário nacional.',
 'Linguagens', 'LCT_H15'),

('LCT_H18', 'LCT H18 — Progressão temática e estrutura de textos',
 'Identificar os elementos que concorrem para a progressão temática e para a organização e estruturação de textos de diferentes gêneros.',
 'Linguagens', NULL),
('LCT_H19', 'LCT H19 — Função da linguagem em situações de interlocução',
 'Analisar a função da linguagem predominante nos textos em situações específicas de interlocução.',
 'Linguagens', 'LCT_H18'),
('LCT_H20', 'LCT H20 — Patrimônio linguístico e identidade nacional',
 'Reconhecer a importância do patrimônio linguístico para a preservação da memória e da identidade nacional.',
 'Linguagens', 'LCT_H18'),

('LCT_H21', 'LCT H21 — Recursos verbais e não-verbais para mudança de comportamento',
 'Reconhecer em textos de diferentes gêneros, recursos verbais e não-verbais utilizados para criar e mudar comportamentos.',
 'Linguagens', NULL),
('LCT_H22', 'LCT H22 — Opiniões e recursos linguísticos em diferentes textos',
 'Relacionar, em diferentes textos, opiniões, temas, assuntos e recursos linguísticos.',
 'Linguagens', 'LCT_H21'),
('LCT_H23', 'LCT H23 — Objetivos e público-alvo de um texto',
 'Inferir em um texto quais são os objetivos de seu produtor e quem é seu público alvo.',
 'Linguagens', 'LCT_H21'),
('LCT_H24', 'LCT H24 — Estratégias argumentativas',
 'Reconhecer no texto estratégias argumentativas empregadas para o convencimento do público.',
 'Linguagens', 'LCT_H21'),

('LCT_H25', 'LCT H25 — Variedades linguísticas',
 'Identificar, em textos de diferentes gêneros, as marcas linguísticas que singularizam as variedades linguísticas sociais, regionais e de registro.',
 'Linguagens', NULL),
('LCT_H26', 'LCT H26 — Variedades e uso social',
 'Relacionar as variedades linguísticas a situações específicas de uso social.',
 'Linguagens', 'LCT_H25'),
('LCT_H27', 'LCT H27 — Norma padrão da língua portuguesa',
 'Reconhecer os usos da norma padrão da língua portuguesa nas diferentes situações de comunicação.',
 'Linguagens', 'LCT_H25'),

('LCT_H28', 'LCT H28 — Impacto social das tecnologias de comunicação',
 'Reconhecer a função e o impacto social das diferentes tecnologias da comunicação e informação.',
 'Linguagens', NULL),
('LCT_H29', 'LCT H29 — Linguagens das tecnologias de comunicação',
 'Identificar pela análise de suas linguagens as tecnologias da comunicação e informação.',
 'Linguagens', 'LCT_H28'),
('LCT_H30', 'LCT H30 — Tecnologia, sociedade e conhecimento',
 'Relacionar as tecnologias de comunicação e informação ao desenvolvimento das sociedades e ao conhecimento que elas produzem.',
 'Linguagens', 'LCT_H28'),


-- ─── MATEMÁTICA ──────────────────────────────────────────
('MAT_H01', 'MAT H1 — Representações e significados dos números',
 'Reconhecer, no contexto social, diferentes significados e representações dos números e operações.',
 'Matemática', NULL),
('MAT_H02', 'MAT H2 — Padrões numéricos e contagem',
 'Identificar padrões numéricos ou princípios de contagem.',
 'Matemática', 'MAT_H01'),
('MAT_H03', 'MAT H3 — Resolução de situação-problema numérica',
 'Resolver situação-problema envolvendo conhecimentos numéricos.',
 'Matemática', 'MAT_H01'),
('MAT_H04', 'MAT H4 — Razoabilidade de resultados numéricos',
 'Avaliar a razoabilidade de um resultado numérico na construção de argumentos sobre afirmações quantitativas.',
 'Matemática', 'MAT_H01'),
('MAT_H05', 'MAT H5 — Intervenção na realidade com conhecimentos numéricos',
 'Avaliar propostas de intervenção na realidade utilizando conhecimentos numéricos.',
 'Matemática', 'MAT_H01'),

('MAT_H06', 'MAT H6 — Localização e movimentação no espaço',
 'Interpretar a localização e a movimentação de pessoas/objetos no espaço tridimensional e sua representação bidimensional.',
 'Matemática', NULL),
('MAT_H07', 'MAT H7 — Características de figuras planas e espaciais',
 'Identificar características de figuras planas ou espaciais.',
 'Matemática', 'MAT_H06'),
('MAT_H08', 'MAT H8 — Resolução de situação-problema geométrica',
 'Resolver situação-problema que envolva conhecimentos geométricos de espaço e forma.',
 'Matemática', 'MAT_H06'),
('MAT_H09', 'MAT H9 — Argumentação com conhecimentos geométricos',
 'Utilizar conhecimentos geométricos de espaço e forma na seleção de argumentos para solução de problemas do cotidiano.',
 'Matemática', 'MAT_H06'),

('MAT_H10', 'MAT H10 — Relações entre grandezas e medidas',
 'Identificar relações entre grandezas e unidades de medida.',
 'Matemática', NULL),
('MAT_H11', 'MAT H11 — Escalas',
 'Utilizar a noção de escalas na leitura de representação de situação do cotidiano.',
 'Matemática', 'MAT_H10'),
('MAT_H12', 'MAT H12 — Resolução de situação-problema com medidas',
 'Resolver situação-problema que envolva medidas de grandezas.',
 'Matemática', 'MAT_H10'),
('MAT_H13', 'MAT H13 — Avaliação de resultados de medição',
 'Avaliar o resultado de uma medição na construção de um argumento consistente.',
 'Matemática', 'MAT_H10'),
('MAT_H14', 'MAT H14 — Intervenção na realidade com grandezas e medidas',
 'Avaliar proposta de intervenção na realidade utilizando conhecimentos geométricos relacionados a grandezas e medidas.',
 'Matemática', 'MAT_H10'),

('MAT_H15', 'MAT H15 — Dependência entre grandezas',
 'Identificar a relação de dependência entre grandezas.',
 'Matemática', NULL),
('MAT_H16', 'MAT H16 — Grandezas proporcionais',
 'Resolver situação-problema envolvendo a variação de grandezas, direta ou inversamente proporcionais.',
 'Matemática', 'MAT_H15'),
('MAT_H17', 'MAT H17 — Variação de grandezas como argumento',
 'Analisar informações envolvendo a variação de grandezas como recurso para a construção de argumentação.',
 'Matemática', 'MAT_H15'),
('MAT_H18', 'MAT H18 — Intervenção na realidade com variação de grandezas',
 'Avaliar propostas de intervenção na realidade envolvendo variação de grandezas.',
 'Matemática', 'MAT_H15'),

('MAT_H19', 'MAT H19 — Representações algébricas',
 'Identificar representações algébricas que expressem a relação entre grandezas.',
 'Matemática', NULL),
('MAT_H20', 'MAT H20 — Interpretação de gráfico cartesiano',
 'Interpretar gráfico cartesiano que represente relações entre grandezas.',
 'Matemática', 'MAT_H19'),
('MAT_H21', 'MAT H21 — Modelagem e resolução algébrica',
 'Resolver situação-problema cuja modelagem envolva conhecimentos algébricos.',
 'Matemática', 'MAT_H19'),
('MAT_H22', 'MAT H22 — Argumentação algébrica e geométrica',
 'Utilizar conhecimentos algébricos/geométricos como recurso para a construção de argumentação.',
 'Matemática', 'MAT_H19'),
('MAT_H23', 'MAT H23 — Intervenção na realidade com álgebra',
 'Avaliar propostas de intervenção na realidade utilizando conhecimentos algébricos.',
 'Matemática', 'MAT_H19'),

('MAT_H24', 'MAT H24 — Inferências em gráficos e tabelas',
 'Utilizar informações expressas em gráficos ou tabelas para fazer inferências.',
 'Matemática', NULL),
('MAT_H25', 'MAT H25 — Resolução de problemas com dados',
 'Resolver problema com dados apresentados em tabelas ou gráficos.',
 'Matemática', 'MAT_H24'),
('MAT_H26', 'MAT H26 — Argumentação com dados de gráficos',
 'Analisar informações expressas em gráficos ou tabelas como recurso para a construção de argumentos.',
 'Matemática', 'MAT_H24'),
('MAT_H27', 'MAT H27 — Medidas estatísticas',
 'Calcular medidas de tendência central ou de dispersão de um conjunto de dados.',
 'Matemática', 'MAT_H24'),
('MAT_H28', 'MAT H28 — Estatística e probabilidade em situações-problema',
 'Resolver situação-problema que envolva conhecimentos de estatística e probabilidade.',
 'Matemática', 'MAT_H24'),
('MAT_H29', 'MAT H29 — Argumentação com estatística e probabilidade',
 'Utilizar conhecimentos de estatística e probabilidade como recurso para a construção de argumentação.',
 'Matemática', 'MAT_H24'),
('MAT_H30', 'MAT H30 — Intervenção na realidade com estatística',
 'Avaliar propostas de intervenção na realidade utilizando conhecimentos de estatística e probabilidade.',
 'Matemática', 'MAT_H24'),


-- ─── CIÊNCIAS DA NATUREZA ────────────────────────────────
('CNT_H01', 'CNT H1 — Fenômenos ondulatórios e oscilatórios',
 'Reconhecer características ou propriedades de fenômenos ondulatórios ou oscilatórios, relacionando-os a seus usos em diferentes contextos.',
 'Ciências da Natureza', NULL),
('CNT_H02', 'CNT H2 — Ciência e tecnologia na solução de problemas',
 'Associar a solução de problemas de comunicação, transporte, saúde ou outro ao correspondente desenvolvimento científico e tecnológico.',
 'Ciências da Natureza', 'CNT_H01'),
('CNT_H03', 'CNT H3 — Senso comum vs. interpretação científica',
 'Confrontar interpretações científicas com interpretações baseadas no senso comum ao longo do tempo ou em diferentes culturas.',
 'Ciências da Natureza', NULL),
('CNT_H04', 'CNT H4 — Intervenção no ambiente e sustentabilidade',
 'Avaliar propostas de intervenção no ambiente considerando a qualidade de vida humana ou medidas de conservação da biodiversidade.',
 'Ciências da Natureza', NULL),

('CNT_H05', 'CNT H5 — Circuitos elétricos de uso cotidiano',
 'Dimensionar circuitos ou dispositivos elétricos de uso cotidiano.',
 'Ciências da Natureza', NULL),
('CNT_H06', 'CNT H6 — Manuais e sistemas tecnológicos',
 'Relacionar informações para compreender manuais de instalação ou utilização de aparelhos ou sistemas tecnológicos de uso comum.',
 'Ciências da Natureza', NULL),
('CNT_H07', 'CNT H7 — Testes e comparação de materiais',
 'Selecionar testes de controle, parâmetros ou critérios para comparação de materiais e produtos, visando defesa do consumidor ou saúde.',
 'Ciências da Natureza', NULL),

('CNT_H08', 'CNT H8 — Obtenção e transformação de recursos naturais',
 'Identificar etapas em processos de obtenção, transformação, utilização ou reciclagem de recursos naturais, energéticos ou matérias-primas.',
 'Ciências da Natureza', NULL),
('CNT_H09', 'CNT H9 — Ciclos biogeoquímicos e fluxo de energia',
 'Compreender a importância dos ciclos biogeoquímicos ou do fluxo de energia para a vida.',
 'Ciências da Natureza', 'CNT_H08'),
('CNT_H10', 'CNT H10 — Perturbações ambientais e poluição',
 'Analisar perturbações ambientais, identificando fontes, transporte e/ou destino dos poluentes ou prevendo efeitos em sistemas naturais.',
 'Ciências da Natureza', 'CNT_H08'),
('CNT_H11', 'CNT H11 — Biotecnologia e ética',
 'Reconhecer benefícios, limitações e aspectos éticos da biotecnologia, considerando estruturas e processos biológicos envolvidos.',
 'Ciências da Natureza', NULL),
('CNT_H12', 'CNT H12 — Impactos ambientais de atividades humanas',
 'Avaliar impactos em ambientes naturais decorrentes de atividades sociais ou econômicas, considerando interesses contraditórios.',
 'Ciências da Natureza', NULL),

('CNT_H13', 'CNT H13 — Mecanismos de transmissão da vida',
 'Reconhecer mecanismos de transmissão da vida, prevendo ou explicando a manifestação de características dos seres vivos.',
 'Ciências da Natureza', NULL),
('CNT_H14', 'CNT H14 — Padrões em processos vitais dos organismos',
 'Identificar padrões em fenômenos e processos vitais dos organismos, como equilíbrio interno, defesa e relações com o ambiente.',
 'Ciências da Natureza', 'CNT_H13'),
('CNT_H15', 'CNT H15 — Modelos e experimentos para fenômenos biológicos',
 'Interpretar modelos e experimentos para explicar fenômenos ou processos biológicos em qualquer nível de organização.',
 'Ciências da Natureza', 'CNT_H13'),
('CNT_H16', 'CNT H16 — Evolução e taxonomia',
 'Compreender o papel da evolução na produção de padrões, processos biológicos ou na organização taxonômica dos seres vivos.',
 'Ciências da Natureza', 'CNT_H13'),

('CNT_H17', 'CNT H17 — Linguagens e representações nas ciências',
 'Relacionar informações apresentadas em diferentes formas de linguagem e representação usadas nas ciências físicas, químicas ou biológicas.',
 'Ciências da Natureza', NULL),
('CNT_H18', 'CNT H18 — Propriedades de materiais e tecnologia',
 'Relacionar propriedades físicas, químicas ou biológicas de produtos, sistemas ou procedimentos tecnológicos às finalidades a que se destinam.',
 'Ciências da Natureza', NULL),
('CNT_H19', 'CNT H19 — Métodos científicos para problemas socioambientais',
 'Avaliar métodos, processos ou procedimentos das ciências naturais que contribuam para diagnosticar ou solucionar problemas sociais, econômicos ou ambientais.',
 'Ciências da Natureza', NULL),

('CNT_H20', 'CNT H20 — Movimentos e causas/efeitos (Física)',
 'Caracterizar causas ou efeitos dos movimentos de partículas, substâncias, objetos ou corpos celestes.',
 'Ciências da Natureza', NULL),
('CNT_H21', 'CNT H21 — Termodinâmica e eletromagnetismo',
 'Utilizar leis físicas e/ou químicas para interpretar processos naturais ou tecnológicos inseridos no contexto da termodinâmica e/ou do eletromagnetismo.',
 'Ciências da Natureza', 'CNT_H20'),
('CNT_H22', 'CNT H22 — Radiação e matéria',
 'Compreender fenômenos decorrentes da interação entre a radiação e a matéria em suas manifestações naturais, tecnológicas ou biológicas.',
 'Ciências da Natureza', 'CNT_H20'),
('CNT_H23', 'CNT H23 — Geração e uso de energia',
 'Avaliar possibilidades de geração, uso ou transformação de energia em ambientes específicos, considerando implicações éticas, ambientais e sociais.',
 'Ciências da Natureza', 'CNT_H20'),

('CNT_H24', 'CNT H24 — Códigos e nomenclatura química',
 'Utilizar códigos e nomenclatura da química para caracterizar materiais, substâncias ou transformações químicas.',
 'Ciências da Natureza', NULL),
('CNT_H25', 'CNT H25 — Caracterização de materiais e substâncias (Química)',
 'Caracterizar materiais ou substâncias, identificando etapas, rendimentos ou implicações biológicas, sociais, econômicas ou ambientais.',
 'Ciências da Natureza', 'CNT_H24'),
('CNT_H26', 'CNT H26 — Recursos energéticos e impactos químicos',
 'Avaliar implicações sociais, ambientais e/ou econômicas na produção ou no consumo de recursos energéticos ou minerais.',
 'Ciências da Natureza', 'CNT_H24'),
('CNT_H27', 'CNT H27 — Intervenção ambiental com conhecimentos químicos',
 'Avaliar propostas de intervenção no meio ambiente aplicando conhecimentos químicos, observando riscos ou benefícios.',
 'Ciências da Natureza', 'CNT_H24'),

('CNT_H28', 'CNT H28 — Adaptações dos organismos (Biologia)',
 'Associar características adaptativas dos organismos com seu modo de vida ou com seus limites de distribuição em diferentes ambientes.',
 'Ciências da Natureza', NULL),
('CNT_H29', 'CNT H29 — Experimentos com seres vivos',
 'Interpretar experimentos ou técnicas que utilizam seres vivos, analisando implicações para o ambiente, a saúde ou a produção de alimentos.',
 'Ciências da Natureza', 'CNT_H28'),
('CNT_H30', 'CNT H30 — Saúde individual, coletiva e ambiental',
 'Avaliar propostas de alcance individual ou coletivo que visem à preservação e implementação da saúde individual, coletiva ou do ambiente.',
 'Ciências da Natureza', 'CNT_H28'),


-- ─── CIÊNCIAS HUMANAS ────────────────────────────────────
('CHT_H01', 'CHT H1 — Interpretação histórica e geográfica de fontes culturais',
 'Interpretar historicamente e/ou geograficamente fontes documentais acerca de aspectos da cultura.',
 'Ciências Humanas', NULL),
('CHT_H02', 'CHT H2 — Produção da memória pelas sociedades',
 'Analisar a produção da memória pelas sociedades humanas.',
 'Ciências Humanas', 'CHT_H01'),
('CHT_H03', 'CHT H3 — Cultura do presente e seus processos históricos',
 'Associar as manifestações culturais do presente aos seus processos históricos.',
 'Ciências Humanas', 'CHT_H01'),
('CHT_H04', 'CHT H4 — Diferentes pontos de vista sobre cultura',
 'Comparar pontos de vista expressos em diferentes fontes sobre determinado aspecto da cultura.',
 'Ciências Humanas', 'CHT_H01'),
('CHT_H05', 'CHT H5 — Diversidade do patrimônio cultural e artístico',
 'Identificar as manifestações ou representações da diversidade do patrimônio cultural e artístico em diferentes sociedades.',
 'Ciências Humanas', 'CHT_H01'),

('CHT_H06', 'CHT H6 — Representações cartográficas dos espaços geográficos',
 'Interpretar diferentes representações gráficas e cartográficas dos espaços geográficos.',
 'Ciências Humanas', NULL),
('CHT_H07', 'CHT H7 — Relações de poder entre nações',
 'Identificar os significados histórico-geográficos das relações de poder entre as nações.',
 'Ciências Humanas', 'CHT_H06'),
('CHT_H08', 'CHT H8 — Estados nacionais e fluxos populacionais',
 'Analisar a ação dos estados nacionais na dinâmica dos fluxos populacionais e no enfrentamento de problemas econômico-sociais.',
 'Ciências Humanas', 'CHT_H06'),
('CHT_H09', 'CHT H9 — Organizações políticas e socioeconômicas',
 'Comparar o significado histórico-geográfico das organizações políticas e socioeconômicas em escala local, regional ou mundial.',
 'Ciências Humanas', 'CHT_H06'),
('CHT_H10', 'CHT H10 — Movimentos sociais e transformação histórico-geográfica',
 'Reconhecer a dinâmica da organização dos movimentos sociais e a importância da participação coletiva na transformação da realidade.',
 'Ciências Humanas', 'CHT_H06'),

('CHT_H11', 'CHT H11 — Registros de grupos sociais no tempo e no espaço',
 'Identificar registros de práticas de grupos sociais no tempo e no espaço.',
 'Ciências Humanas', NULL),
('CHT_H12', 'CHT H12 — Justiça como instituição social',
 'Analisar o papel da justiça como instituição na organização das sociedades.',
 'Ciências Humanas', 'CHT_H11'),
('CHT_H13', 'CHT H13 — Movimentos sociais e disputas de poder',
 'Analisar a atuação dos movimentos sociais que contribuíram para mudanças ou rupturas em processos de disputa pelo poder.',
 'Ciências Humanas', 'CHT_H11'),
('CHT_H14', 'CHT H14 — Análise crítica de instituições sociais',
 'Comparar diferentes pontos de vista sobre situação ou fatos de natureza histórico-geográfica acerca das instituições sociais, políticas e econômicas.',
 'Ciências Humanas', 'CHT_H11'),
('CHT_H15', 'CHT H15 — Conflitos culturais, sociais e políticos',
 'Avaliar criticamente conflitos culturais, sociais, políticos, econômicos ou ambientais ao longo da história.',
 'Ciências Humanas', 'CHT_H11'),

('CHT_H16', 'CHT H16 — Técnicas, tecnologias e organização do trabalho',
 'Identificar registros sobre o papel das técnicas e tecnologias na organização do trabalho e/ou da vida social.',
 'Ciências Humanas', NULL),
('CHT_H17', 'CHT H17 — Novas tecnologias e territorialização da produção',
 'Analisar fatores que explicam o impacto das novas tecnologias no processo de territorialização da produção.',
 'Ciências Humanas', 'CHT_H16'),
('CHT_H18', 'CHT H18 — Processos de produção e circulação de riquezas',
 'Analisar diferentes processos de produção ou circulação de riquezas e suas implicações sócio-espaciais.',
 'Ciências Humanas', 'CHT_H16'),
('CHT_H19', 'CHT H19 — Tecnologia e uso dos espaços rural e urbano',
 'Reconhecer as transformações técnicas e tecnológicas que determinam as formas de uso e apropriação dos espaços rural e urbano.',
 'Ciências Humanas', 'CHT_H16'),
('CHT_H20', 'CHT H20 — Tecnologia, vida social e mundo do trabalho',
 'Selecionar argumentos favoráveis ou contrários às modificações impostas pelas novas tecnologias à vida social e ao mundo do trabalho.',
 'Ciências Humanas', 'CHT_H16'),

('CHT_H21', 'CHT H21 — Meios de comunicação e vida social',
 'Identificar o papel dos meios de comunicação na construção da vida social.',
 'Ciências Humanas', NULL),
('CHT_H22', 'CHT H22 — Lutas sociais e políticas públicas',
 'Analisar as lutas sociais e conquistas obtidas no que se refere às mudanças nas legislações ou nas políticas públicas.',
 'Ciências Humanas', 'CHT_H21'),
('CHT_H23', 'CHT H23 — Ética e estrutura política das sociedades',
 'Analisar a importância dos valores éticos na estruturação política das sociedades.',
 'Ciências Humanas', 'CHT_H21'),
('CHT_H24', 'CHT H24 — Cidadania e democracia',
 'Relacionar cidadania e democracia na organização das sociedades.',
 'Ciências Humanas', 'CHT_H21'),
('CHT_H25', 'CHT H25 — Inclusão social',
 'Identificar estratégias que promovam formas de inclusão social.',
 'Ciências Humanas', 'CHT_H21'),

('CHT_H26', 'CHT H26 — Ocupação dos meios físicos',
 'Identificar em fontes diversas o processo de ocupação dos meios físicos e as relações da vida humana com a paisagem.',
 'Ciências Humanas', NULL),
('CHT_H27', 'CHT H27 — Interações sociedade e meio físico',
 'Analisar de maneira crítica as interações da sociedade com o meio físico, levando em consideração aspectos históricos e/ou geográficos.',
 'Ciências Humanas', 'CHT_H26'),
('CHT_H28', 'CHT H28 — Tecnologia e impactos socioambientais',
 'Relacionar o uso das tecnologias com os impactos socioambientais em diferentes contextos histórico-geográficos.',
 'Ciências Humanas', 'CHT_H26'),
('CHT_H29', 'CHT H29 — Recursos naturais e espaço geográfico',
 'Reconhecer a função dos recursos naturais na produção do espaço geográfico, relacionando-os com as mudanças provocadas pelas ações humanas.',
 'Ciências Humanas', 'CHT_H26'),
('CHT_H30', 'CHT H30 — Preservação e degradação da vida no planeta',
 'Avaliar as relações entre preservação e degradação da vida no planeta nas diferentes escalas.',
 'Ciências Humanas', 'CHT_H26');


-- ============================================================
-- 3. SUBTRILHAS DIDÁTICAS (Opção B — agrupamento por tema)
--    Habilidade principal de cada grupo indicada em comentário
-- ============================================================

INSERT INTO subtrilhas (trilha_id, habilidade_id, titulo, descricao, ordem) VALUES

-- ─── LINGUAGENS ──────────────────────────────────────────
('00000000-1000-0000-0000-000000000001', 'LCT_H18',
 'Interpretação de Texto e Gêneros Textuais',
 'Progressão temática, estrutura de textos, gêneros discursivos e funções da linguagem. (H18-H20)',
 1),
('00000000-1000-0000-0000-000000000001', 'LCT_H21',
 'Argumentação e Leitura Crítica',
 'Recursos argumentativos, estratégias de convencimento, opiniões e objetivos do texto. (H21-H24)',
 2),
('00000000-1000-0000-0000-000000000001', 'LCT_H25',
 'Língua Portuguesa: Norma e Variação',
 'Variedades linguísticas, norma padrão, registros formal e informal. (H25-H27)',
 3),
('00000000-1000-0000-0000-000000000001', 'LCT_H15',
 'Literatura Brasileira',
 'Texto literário, contexto histórico-social, concepções artísticas e patrimônio literário. (H15-H17)',
 4),
('00000000-1000-0000-0000-000000000001', 'LCT_H05',
 'Língua Inglesa',
 'Vocabulário, estruturas linguísticas e interpretação de textos em inglês. (H5-H8)',
 5),
('00000000-1000-0000-0000-000000000001', 'LCT_H09',
 'Linguagem Corporal, Arte e Cultura',
 'Manifestações corporais, funções da arte e diversidade artística e cultural. (H9-H14)',
 6),
('00000000-1000-0000-0000-000000000001', 'LCT_H01',
 'Tecnologia, Comunicação e Informação',
 'Impacto das tecnologias, linguagens digitais e desenvolvimento das sociedades. (H1-H4, H28-H30)',
 7),

-- ─── MATEMÁTICA ──────────────────────────────────────────
('00000000-2000-0000-0000-000000000001', 'MAT_H01',
 'Números e Operações',
 'Conjuntos numéricos, padrões numéricos, operações e razoabilidade de resultados. (H1-H5)',
 1),
('00000000-2000-0000-0000-000000000001', 'MAT_H06',
 'Geometria e Formas',
 'Figuras planas e espaciais, localização, movimentação e resolução de problemas geométricos. (H6-H9)',
 2),
('00000000-2000-0000-0000-000000000001', 'MAT_H10',
 'Grandezas, Medidas e Escalas',
 'Unidades de medida, escalas, resolução de situações com medidas e grandezas. (H10-H14)',
 3),
('00000000-2000-0000-0000-000000000001', 'MAT_H15',
 'Funções, Álgebra e Proporcionalidade',
 'Dependência entre grandezas, proporcionalidade, modelagem algébrica e gráficos cartesianos. (H15-H23)',
 4),
('00000000-2000-0000-0000-000000000001', 'MAT_H24',
 'Estatística e Probabilidade',
 'Leitura de gráficos e tabelas, medidas estatísticas, probabilidade e análise de dados. (H24-H30)',
 5),

-- ─── CIÊNCIAS DA NATUREZA ────────────────────────────────
('00000000-3000-0000-0000-000000000001', 'CNT_H20',
 'Física',
 'Movimentos, forças, termodinâmica, eletromagnetismo, radiação, energia e ondas. (H20-H23, H1, H5-H6)',
 1),
('00000000-3000-0000-0000-000000000001', 'CNT_H24',
 'Química',
 'Nomenclatura, caracterização de materiais, recursos energéticos e intervenção ambiental. (H24-H27)',
 2),
('00000000-3000-0000-0000-000000000001', 'CNT_H13',
 'Biologia',
 'Transmissão da vida, processos vitais, modelos biológicos, evolução e adaptações. (H13-H16, H28-H30)',
 3),
('00000000-3000-0000-0000-000000000001', 'CNT_H03',
 'Ciência, Tecnologia e Sociedade',
 'Senso comum vs. ciência, biotecnologia, impactos ambientais, ciclos biogeoquímicos e sustentabilidade. (H2-H4, H7-H12, H17-H19)',
 4),

-- ─── CIÊNCIAS HUMANAS ────────────────────────────────────
('00000000-4000-0000-0000-000000000001', 'CHT_H01',
 'História e Cultura',
 'Fontes documentais, memória, manifestações culturais, patrimônio e conflitos históricos. (H1-H5, H11-H15)',
 1),
('00000000-4000-0000-0000-000000000001', 'CHT_H06',
 'Geografia',
 'Cartografia, espaços geográficos, fluxos populacionais, organizações políticas e movimentos sociais. (H6-H10, H26-H30)',
 2),
('00000000-4000-0000-0000-000000000001', 'CHT_H21',
 'Cidadania, Democracia e Direitos',
 'Meios de comunicação, lutas sociais, ética, democracia e inclusão social. (H21-H25)',
 3),
('00000000-4000-0000-0000-000000000001', 'CHT_H16',
 'Tecnologia, Trabalho e Sociedade',
 'Técnicas, territorialização da produção, processos econômicos e impacto tecnológico no trabalho. (H16-H20)',
 4),

-- ─── REDAÇÃO ─────────────────────────────────────────────
('00000000-5000-0000-0000-000000000001', NULL,
 'Estrutura da Redação Dissertativo-Argumentativa',
 'Introdução, desenvolvimento, conclusão e o modelo exigido pelo ENEM.',
 1),
('00000000-5000-0000-0000-000000000001', NULL,
 'As 5 Competências Avaliadas',
 'Norma culta, compreensão da proposta, argumentação, coesão e proposta de intervenção.',
 2),
('00000000-5000-0000-0000-000000000001', NULL,
 'Repertório Sociocultural e Argumentação',
 'Como usar dados, fatos históricos, citações e conhecimentos de área como argumentos.',
 3),
('00000000-5000-0000-0000-000000000001', NULL,
 'Proposta de Intervenção',
 'Construção de uma proposta detalhada com agente, ação, modo/meio, efeito e respeito aos direitos humanos.',
 4),
('00000000-5000-0000-0000-000000000001', NULL,
 'Coesão, Conectivos e Progressão Textual',
 'Articuladores textuais, referenciação, progressão temática e mecanismos de coesão.',
 5);
